### ISSUE TITLE
[question] angular universal support

### ISSUE THREAD

**Issue by ysus** [fulls1z3/ngx-ps#2]
this repo works with angular universal

`PerfectScrollbarModule.forRoot({
      provide: PerfectScrollbarLoader,
      useFactory: (perfectScrollbarFactory)
    }),`
when i set this configuration i have the following error

Argument of type '{ provide: typeof PerfectScrollbarLoader; useFactory: () => PerfectScrollbarLoader; }' is not assignable to parameter of type 'PerfectScrollbarSettings'.
  Object literal may only specify known properties, and 'provide' does not exist in type 'PerfectScrollbarSettings'.

**Comment by fulls1z3** [comment]
@ysus I have just tried the standard implementation on `README`, is it possible for you to let me know about the version numbers of angular and related packages? Also, it would be helpful if you could upload your `app.module` here.

**Comment by fulls1z3** [comment]
@ysus as far as I see you're passing a lambda expression as the `useFactory` param, is it true? If so, it's normal that the `ngc` throws such an exception - you can only pass an `exported function` to be used at `useFactory`.

**Comment by ysus** [comment]
hi @fulls1z3  thanks for your answare im using the frozenpandaz repo :
https://github.com/FrozenPandaz/ng-universal-demo
and all your utilities works perfect, thanks for shared  but with thas i have the problem that i mentioted last
this is my package 
`{
  "name": "ng-universal-demo",
  "version": "1.0.0",
  "main": "index.js",
  "repository": {},
  "scripts": {
    "start": "npm run build && npm run server",
    "build": "webpack",
    "build:aot": "webpack --env.aot --env.client & webpack --env.aot --env.server",
    "build:prod": "webpack --env.aot --env.client -p & webpack --env.aot --env.server",
    "prebuild": "npm run clean",
    "prebuild:aot": "npm run clean",
    "prebuild:prod": "npm run clean",
    "clean": "rimraf dist",
    "server": "nodemon dist/server.js",
    "watch": "webpack --watch"
  },
  "engines": {
    "node": ">=6.0.0"
  },
  "license": "MIT",
  "dependencies": {
    "@angular/animations": "^4.0.0",
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/platform-server": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@nguniversal/express-engine": "^1.0.0-beta.0",
    "@ngx-cache/core": "^0.4.0-beta.1",
    "@ngx-meta/core": "^0.4.0-rc.2",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "@ngx-universal/state-transfer": "^0.4.0-beta.1",
    "@ngx-universal/translate-loader": "^0.4.0-beta.1",
    "bulma": "^0.4.3",
    "express": "^4.15.2",
    "font-awesome": "^4.7.0",
    "ngx-ps": "^0.2.0-alpha.2",
    "rxjs": "^5.3.0",
    "xhr2": "^0.1.4",
    "zone.js": "^0.8.8"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^4.0.0",
    "@ngtools/webpack": "^1.2.14",
    "@types/express": "^4.0.35",
    "@types/node": "^7.0.8",
    "autoprefixer": "^7.1.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.4",
    "exports-loader": "^0.6.4",
    "extract-text-webpack-plugin": "^2.1.0",
    "file-loader": "^0.11.2",
    "html-webpack-plugin": "^2.28.0",
    "node-sass": "^4.5.3",
    "nodemon": "^1.11.0",
    "postcss-loader": "^2.0.6",
    "raw-loader": "^0.5.1",
    "resolve-url-loader": "^2.0.2",
    "rimraf": "^2.6.1",
    "sass-loader": "^6.0.5",
    "script-ext-html-webpack-plugin": "^1.7.1",
    "style-loader": "^0.18.2",
    "to-string-loader": "^1.1.5",
    "typescript": "^2.2.1",
    "webpack": "^2.2.1",
    "webpack-merge": "^4.0.0"
  }
}
`

this is my module:

`
.....

///
import { TransferHttpModule } from '../modules/transfer-http/transfer-http.module';
import { TranslateModule, TranslateLoader } from "@ngx-translate/core";
import { TranslateHttpLoader } from "@ngx-translate/http-loader";
import { UniversalTranslateLoader } from '@ngx-universal/translate-loader';
import { HttpTransferModule } from '@ngx-universal/state-transfer';
import { CacheModule } from '@ngx-cache/core';
//
import { APP_CONFIG, APP_DI_CONFIG } from "./shared/api-config/app-config.constants";

//
import { MetaModule } from '@ngx-meta/core';
import { PerfectScrollbarModule, PerfectScrollbarLoader, PerfectScrollbarStaticLoader } from 'ngx-ps';


export function translateFactory(platformId: any, http: Http): TranslateLoader {
  const browserLoader = new TranslateHttpLoader(http);

  return new UniversalTranslateLoader(platformId, browserLoader,'./dist/assets/i18n/', '.json');
}

export function perfectScrollbarFactory(): PerfectScrollbarLoader {
  return new PerfectScrollbarStaticLoader({
    "suppressScrollX": true,
    "swipePropagation": false
  });
}

export { AppComponent };

@NgModule({
  declarations: [
    AppComponent,
    BannerComponent,
    DestinationsComponent,
    DiscoverComponent,
    PromotionsComponent,
    LandingComponent,
    PromotionsListComponent,
    PromotionsDetailComponent,
    AuthenticatedUserComponent,
    AuthenticatedPageComponent,
    DestinationPanelComponent,
    CarouselElementComponent,
    SlideElementComponent,
    CarouselPanelComponent,
    SvgIconComponent,
    DestinationsListComponent,
    DestinationListPanelComponent,
    PromotionCardDescriptionComponent,
    PromotionCardActivitiesComponent,
    ProfilingFilterBarComponent,
    SearchHotelBarComponent,
    InfoCardComponent,
    ProfilingFilterButtonsComponent,
    HotelDestinationFilter,
    ModalComponent,
    TempComponent,

    TipsComponent,
    FaqsComponent,
    MissionComponent,

    //pipes
    dateFormatPipe,
    MyFilterPipe,
    ProfileFilterPipe,
    MyFilterPromosPipe,
    MyFilterPromosPipe2,
    

    //partials
    PromotionsInfoCard,
    SitemapPromotions

  ],
  imports: [
        //
    FwModule,
    BrowserModule,
    TransferHttpModule,
    HttpTransferModule.forRoot(),
    MetaModule.forRoot(),
    CacheModule.forRoot(),

    RouterModule.forRoot(appRoutes),
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: (translateFactory),
        deps: [PLATFORM_ID, Http]
      }
    }),

    PerfectScrollbarModule.forRoot({ provide: PerfectScrollbarLoader, useFactory: (perfectScrollbarFactory) }),
    FormsModule,
    HttpModule,
  ],
  exports: [AppComponent],
  providers: [
    UserService,
    { provide: UserApi, useExisting: UserService },
    AuthGuard,
    AppDataService,
    SvgIconRegistryService,
    PromotionsResolver,
    PromotionsListResolver,
    PromotionsDetailResolver,
    DestinationsResolver,
    DestinationsListResolve,
    DiscoverResolver,
    LandingResolver,
    TempResolver,

    TipsResolver,
    FaqsResolver,
    MissionResolver,

    {
      provide: APP_CONFIG,
      useValue: APP_DI_CONFIG
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
  constructor( @Inject(PLATFORM_ID) private readonly platformId: any) {
  }
}
`

thanks.

**Comment by fulls1z3** [comment]
@ysus according to the package and `app.module` structure, I can see no reasons for `ngx-ps` to do not work. Have you ever tried importing `PerfectScrollbarModule.forRoot()` without any params?

**Comment by ysus** [comment]
hi @fulls1z3  thanks for answer 
![sdfgsdfgs](https://user-images.githubusercontent.com/14302557/28887195-e479c4a0-7781-11e7-896c-af6698dd7de2.png)
this is the message from vs code

**Comment by ysus** [comment]
if i access to the view with the  ps component its works, but when i access to the view directly i have the follwing error:
TypeError: element.getAttribute is not a function
    at getId (C:\src\webapp-intertours\dist\server.js:30519:18)
    at Object.exports.get (C:\src\webapp-intertours\dist\server.js:30543:20)
    at Object.module.exports [as destroy] (C:\src\webapp-intertours\dist\server.js:123012:21)
    at C:\src\webapp-intertours\dist\server.js:87388:75
    at ZoneDelegate.invoke (C:\src\webapp-intertours\dist\server.js:96710:26)
    at Zone.run (C:\src\webapp-intertours\dist\server.js:96460:43)
    at NgZone.runOutsideAngular (C:\src\webapp-intertours\dist\server.js:4467:76)
    at PerfectScrollbarDirective.ngOnDestroy (C:\src\webapp-intertours\dist\server.js:87387:23)
    at callProviderLifecycles (C:\src\webapp-intertours\dist\server.js:11594:18)
    at callElementProvidersLifecycles (C:\src\webapp-intertours\dist\server.js:11563:13)
    at callLifecycleHooksChildrenFirst (C:\src\webapp-intertours\dist\server.js:11547:17)

**Comment by ysus** [comment]
without any params works  fine not show the  message of the image, but i have the same issue it works well  if i access to the view with the ps component from another view(home) its works, but when i access to the view with the ps directive i have the follwing error:


ERROR { Error: Uncaught (in promise): TypeError: element.setAttribute is not a function
TypeError: element.setAttribute is not a function
    at setId (C:\src\webapp-intertours\dist\server.js:30523:11)
    at Object.exports.add (C:\src\webapp-intertours\dist\server.js:30532:3)
    at Object.module.exports [as initialize] (C:\src\webapp-intertours\dist\server.js:123861:21)
    at C:\src\webapp-intertours\dist\server.js:87406:78
    at ZoneDelegate.invoke (C:\src\webapp-intertours\dist\server.js:96710:26)
    at Zone.run (C:\src\webapp-intertours\dist\server.js:96460:43)
    at NgZone.runOutsideAngular (C:\src\webapp-intertours\dist\server.js:4467:76)
    at PerfectScrollbarDirective.ngAfterViewInit (C:\src\webapp-intertours\dist\server.js:87405:23)
    at callProviderLifecycles (C:\src\webapp-intertours\dist\server.js:11588:18)
    at callElementProvidersLifecycles (C:\src\webapp-intertours\dist\server.js:11563:13)
    at resolvePromise (C:\src\webapp-intertours\dist\server.js:97088:31)
    at resolvePromise (C:\src\webapp-intertours\dist\server.js:97059:17)
    at C:\src\webapp-intertours\dist\server.js:97136:17
    at ZoneDelegate.invokeTask (C:\src\webapp-intertours\dist\server.js:96743:31)
    at Object.onInvokeTask (C:\src\webapp-intertours\dist\server.js:4567:37)
    at ZoneDelegate.invokeTask (C:\src\webapp-intertours\dist\server.js:96742:36)
    at Zone.runTask (C:\src\webapp-intertours\dist\server.js:96510:47)
    at drainMicroTaskQueue (C:\src\webapp-intertours\dist\server.js:96903:35)
    at ZoneTask.invoke (C:\src\webapp-intertours\dist\server.js:96809:25)
    at data.args.(anonymous function) (C:\src\webapp-intertours\dist\server.js:97614:25)
  rejection:
   { TypeError: element.setAttribute is not a function
       at setId (C:\src\webapp-intertours\dist\server.js:30523:11)
       at Object.exports.add (C:\src\webapp-intertours\dist\server.js:30532:3)
       at Object.module.exports [as initialize] (C:\src\webapp-intertours\dist\server.js:123861:21)
       at C:\src\webapp-intertours\dist\server.js:87406:78
       at ZoneDelegate.invoke (C:\src\webapp-intertours\dist\server.js:96710:26)
       at Zone.run (C:\src\webapp-intertours\dist\server.js:96460:43)
       at NgZone.runOutsideAngular (C:\src\webapp-intertours\dist\server.js:4467:76)
       at PerfectScrollbarDirective.ngAfterViewInit (C:\src\webapp-intertours\dist\server.js:87405:23)
       at callProviderLifecycles (C:\src\webapp-intertours\dist\server.js:11588:18)
       at callElementProvidersLifecycles (C:\src\webapp-intertours\dist\server.js:11563:13)
     __zone_symbol__currentTask:
      ZoneTask {
        _zone: [Object],
        runCount: 0,
        _zoneDelegates: null,
        _state: 'notScheduled',
        type: 'microTask',
        source: 'Promise.then',
        data: undefined,
        scheduleFn: undefined,
        cancelFn: null,
        callback: [Function],
        invoke: [Function] } },
  promise:
   ZoneAwarePromise {
     __zone_symbol__state: 0,
     __zone_symbol__value:
      { TypeError: element.setAttribute is not a function
          at setId (C:\src\webapp-intertours\dist\server.js:30523:11)
          at Object.exports.add (C:\src\webapp-intertours\dist\server.js:30532:3)
          at Object.module.exports [as initialize] (C:\src\webapp-intertours\dist\server.js:123861:21)
          at C:\src\webapp-intertours\dist\server.js:87406:78
          at ZoneDelegate.invoke (C:\src\webapp-intertours\dist\server.js:96710:26)
          at Zone.run (C:\src\webapp-intertours\dist\server.js:96460:43)
          at NgZone.runOutsideAngular (C:\src\webapp-intertours\dist\server.js:4467:76)
          at PerfectScrollbarDirective.ngAfterViewInit (C:\src\webapp-intertours\dist\server.js:87405:23)
          at callProviderLifecycles (C:\src\webapp-intertours\dist\server.js:11588:18)
          at callElementProvidersLifecycles (C:\src\webapp-intertours\dist\server.js:11563:13) __zone_symbol__currentTask: [Object] } },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [Object],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Object],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Object],
        _invokeZS: [Object],
        _invokeDlgt: [Object],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [Object],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [Object],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [Object],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [Object],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [Object],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'angular',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
ERROR TypeError: element.setAttribute is not a function
    at setId (C:\src\webapp-intertours\dist\server.js:30523:11)
    at Object.exports.add (C:\src\webapp-intertours\dist\server.js:30532:3)
    at Object.module.exports [as initialize] (C:\src\webapp-intertours\dist\server.js:123861:21)
    at C:\src\webapp-intertours\dist\server.js:87406:78
    at ZoneDelegate.invoke (C:\src\webapp-intertours\dist\server.js:96710:26)
    at Zone.run (C:\src\webapp-intertours\dist\server.js:96460:43)
    at NgZone.runOutsideAngular (C:\src\webapp-intertours\dist\server.js:4467:76)
    at PerfectScrollbarDirective.ngAfterViewInit (C:\src\webapp-intertours\dist\server.js:87405:23)
    at callProviderLifecycles (C:\src\webapp-intertours\dist\server.js:11588:18)
    at callElementProvidersLifecycles (C:\src\webapp-intertours\dist\server.js:11563:13)
ERROR TypeError: element.setAttribute is not a function
    at setId (C:\src\webapp-intertours\dist\server.js:30523:11)
    at Object.exports.add (C:\src\webapp-intertours\dist\server.js:30532:3)
    at Object.module.exports [as initialize] (C:\src\webapp-intertours\dist\server.js:123861:21)
    at C:\src\webapp-intertours\dist\server.js:87406:78
    at ZoneDelegate.invoke (C:\src\webapp-intertours\dist\server.js:96710:26)
    at Zone.run (C:\src\webapp-intertours\dist\server.js:96460:43)
    at NgZone.runOutsideAngular (C:\src\webapp-intertours\dist\server.js:4467:76)
    at PerfectScrollbarDirective.ngAfterViewInit (C:\src\webapp-intertours\dist\server.js:87405:23)
    at callProviderLifecycles (C:\src\webapp-intertours\dist\server.js:11588:18)
    at callElementProvidersLifecycles (C:\src\webapp-intertours\dist\server.js:11563:13)
ERROR TypeError: element.setAttribute is not a function
    at setId (C:\src\webapp-intertours\dist\server.js:30523:11)
    at Object.exports.add (C:\src\webapp-intertours\dist\server.js:30532:3)
    at Object.module.exports [as initialize] (C:\src\webapp-intertours\dist\server.js:123861:21)
    at C:\src\webapp-intertours\dist\server.js:87406:78
    at ZoneDelegate.invoke (C:\src\webapp-intertours\dist\server.js:96710:26)
    at Zone.run (C:\src\webapp-intertours\dist\server.js:96460:43)
    at NgZone.runOutsideAngular (C:\src\webapp-intertours\dist\server.js:4467:76)
    at PerfectScrollbarDirective.ngAfterViewInit (C:\src\webapp-intertours\dist\server.js:87405:23)
    at callProviderLifecycles (C:\src\webapp-intertours\dist\server.js:11588:18)
    at callElementProvidersLifecycles (C:\src\webapp-intertours\dist\server.js:11563:13)

**Comment by ysus** [comment]
### this are the lines in ther server.js that generate the error, if i comment  works :
`function getId(element) {
  return element.getAttribute('data-ps-id');
}

function setId(element, id) {
  element.setAttribute('data-ps-id', id);
}

function removeId(element) {
  element.removeAttribute('data-ps-id');
}

exports.add = function (element) {
  var newId = guid();
  setId(element, newId);
  instances[newId] = new Instance(element);
  return instances[newId];
};

exports.remove = function (element) {
  delete instances[getId(element)];
  removeId(element);
};`

TypeError: element.getAttribute is not a function
    at getId (C:\src\webapp-intertours\dist\server.js:31938:18)
    at Object.exports.get (C:\src\webapp-intertours\dist\server.js:31962:20)
    at Object.module.exports [as destroy] (C:\src\webapp-intertours\dist\server.js:139090:21)
    at C:\src\webapp-intertours\dist\server.js:97083:75
    at ZoneDelegate.invoke (C:\src\webapp-intertours\dist\server.js:106322:26)
    at Zone.run (C:\src\webapp-intertours\dist\server.js:106072:43)
    at NgZone.runOutsideAngular (C:\src\webapp-intertours\dist\server.js:4269:83)
    at PerfectScrollbarDirective.ngOnDestroy (C:\src\webapp-intertours\dist\server.js:97082:23)
    at callProviderLifecycles (C:\src\webapp-intertours\dist\server.js:11613:18)
    at callElementProvidersLifecycles (C:\src\webapp-intertours\dist\server.js:11582:13)

but i thinks that is error of perfectscroll

**Comment by ysus** [comment]
finally i can found the solution:
in the view:
`<div *ngIf="isBrowser" class="description-promotion" [perfect-scrollbar]>`
in the component.ts:
```
  constructor(
    @Inject(PLATFORM_ID) public platformId: Object,
    public menuService: MenuService
  ) {
    this.isBrowser = isPlatformBrowser(platformId);

  }
```

thnks so much for the lib
